Adjust for rails 5
CreativeGS/banklink_gs pull request #9
Opened 2019-09-30 13:16 UTC by OlegsBoldirevs

so hasheable_fiedls return hash instead of Parameters

2019-10-01 05:52 UTC, rihardsgrislis requested changes
Versija nav nomainīta.

2019-10-01 05:52 UTC, rihardssceredins commented
@OlegsBoldirevs šis change strādās arī uz vecākiem Rails?

2019-10-01 05:56 UTC, OlegsBoldirevs commented
> @OlegsBoldirevs šis change strādās arī uz vecākiem Rails?

Aha, jo ieprieks hasheable_fields params padevas hash, bet tagad ActiveRecord::Parameters, so vecaja rails hash.to_h strada.

2019-10-09 06:42 UTC, rihardsgrislis approved these changes

2019-10-09 06:44 UTC, merged